### ISSUE TITLE
Preciso falar contigo urgente

### ISSUE THREAD

**Issue by Cidrack** [leomoreira597/projetos#1]
Fala Leonardo, Cid da Cod3r/Formação DEV. Estamos precisando falar com você urgente.

Responde esse email ou manda whatsapp pra gente no 85981548877 por favor.

Obrigado.

**Comment by leomoreira597** [comment]
Olá, o que aconteceu?

Em qui., 17 de out. de 2024, 08:51, Cidrack ***@***.***>
escreveu:

**Comment by Cidrack** [comment]
ME passa teu whatsapp por favor...

**Comment by leomoreira597** [comment]
Meu número é 11 910957737

Em qui., 17 de out. de 2024, 09:17, Cidrack ***@***.***>
escreveu:
